CREATE TABLE STATE(
      ID INTEGER NOT NULL PRIMARY KEY,
			CONST INTEGER NOT NULL UNIQUE,
      CODE TEXT NOT NULL,
			DESC DESCRIPTION
		);
;
CREATE TABLE SOURCEDATA(
			ID INTEGER NOT NULL PRIMARY KEY,
			POINT TEXT NOT NULL UNIQUE,
			LOGIN TEXT,
			PWD TEXT,
      OPERDATE TIMESTAMP DEFAULT (datetime('now')),
			STATE INTEGER, LABEL TEXT, FILEPATH TEXT, PARSER CLOB, CODE TEXT,
      FOREIGN KEY( STATE ) REFERENCES STATE(ID)
		);
;
CREATE VIEW V_SOURCE AS
    SELECT sd.ID,sd.POINT,sd.LABEL,sd.CODE,sd.LOGIN,sd.PWD, sd.PARSER FROM SourceData sd
    WHERE sd.STATE IN (
        SELECT s.ID FROM STATE s
        WHERE s.CONST != 3
      );
CREATE TABLE SCHEDULE( 
    ID INTEGER NOT NULL PRIMARY KEY,
    TIMEPLAN TEXT NOT NULL,
    DAY INTEGER, 
    TYPE INTEGER 
);
CREATE TABLE RADATA( 
    ID INTEGER NOT NULL PRIMARY KEY,
    MSGID INTEGER NOT NULL,
    ROOM INTEGER,
    SQUARE TEXT,
    PRICE TEXT,
    PHONE TEXT,
    SUBWAY TEXT,
    OTHERS CLOB,
    LINK TEXT,
    PAGE TEXT
);
CREATE TABLE RAJOURNAL(
    ID INTEGER NOT NULL PRIMARY KEY,
    OPERDATE TIMESTAMP DEFAULT (datetime('now')),
    LINE TEXT
);
